export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    classNameTheme: "_green",
  },
  {
    id: 2,
    theme: "Research",
    title: "Старая задача",
    date: "30.10.23",
    status: "Без статуса",
    classNameTheme: "_orange",
  },
  {
    id: 3,
    theme: "Research",
    title: "Нужно сделать",
    date: "30.10.23",
    status: "Нужно сделать",
    classNameTheme: "_orange",
  },
  {
    id: 4,
    theme: "Copywriting",
    title: "Старая задача",
    date: "30.10.23",
    status: "В работе",
    classNameTheme: "_purple",
  },
  {
    id: 5,
    theme: "Web Design",
    title: "Card game",
    date: "30.12.23",
    status: "Тестирование",
    classNameTheme: "_green",
  },
  {
    id: 6,
    theme: "Copywriting",
    title: "Встреча",
    date: "30.10.23",
    status: "Готово",
    classNameTheme: "_purple",
  },
];
